global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "source"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["source:8080"]
  - job_name: "processor"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "processor:8091" ]
  - job_name: "sink"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "sink:8092" ]
  - job_name: "dlq"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "dlq:8093" ]
  - job_name: "kafka-exporter"
    static_configs:
      - targets: [ "kafka-exporter:9308" ]