services:

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    extends:
      file: common-config.yml
      service: common-network



  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-init-topics
    depends_on:
      - kafka
    entrypoint: >
      bash -c "
      echo 'Waiting for Kafka...' &&
      cub kafka-ready -b kafka:9092 1 30 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --topic order-topic &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --topic payment-topic &&
      echo 'Topics created'
      "
    extends:
      file: common-config.yml
      service: common-network

  configserver:
    image: "configserver:s1"
    container_name: configserver
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD","curl","-f","http://configserver:8081/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - kafka-init-topics
    extends:
      file: common-config.yml
      service: common-network

  sourceservice:
    image: "source:s1"
    container_name: source
    ports:
      - "8080:8080"
    environment:
       SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
       SPRING_CLOUD_STREAM_BINDINGS_ORDER_OUT_0_DESTINATION: order-topic
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8081/
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: common-network


networks:
  eventdriven:
    driver: "bridge"
